title:             Isaac's Blog
email:             isaacjoyous@outlook.com
description:       A machine learning machine learning
author:            Isaac Joy
baseurl:           ""
url:               "http://isaacjoy.github.io"

# Social Profiles
twitter_username:  isaacjoyous
github_username:   isaacjoy

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
